### ISSUE TITLE
Failed to import "AzureResource" entityType and 	"ResourceId" field.

### ISSUE THREAD

**Issue by hisashin0728** [wortell/AZSentinel#194]
# Environment
PSVersion                      7.2.2
PSEdition                      Core
OS                             Microsoft Windows 10.0.22000
AzSentinel                0.6.21

```none
Windows build number: [run "ver" at a command prompt]
PowerShell version (if applicable):7.2.2

Any other software?
```

# Steps to reproduce
Import the following sample YAML rule. 
https://github.com/hisashin0728/SentinelRule_AzureCISBenchmark/blob/main/CIS_521.yaml

Import-AzSentinelAlertRule -SubscriptionId <SubscriptionID> -WorkspaceName <MyLASpace> -SettingsFile "CIS_521.yaml"
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/55295601/161016134-1cb37e7e-712f-4558-94de-a3eae30af9bb.png">

# Expected behavior
Successfully to import a rule.

# Actual behavior
Succeeded but few parameters are *NOT* imported.

1. Cannot import the specific entity Type "AzureResource"
"Account" and "IP" Types are able to import, but "AzureResource" cannot be imported.
Here is snipped the entityMapping of YAML source. In my understanding, the format is correct (entityType = "AzureResource" and fieldMapping = "ResourceId").

```
entityMappings:
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: AzCustomEntity

```

2. Missed fieldMapping of "Name" identifer. Sentinel imported as "FullName".
The mapping entityType of Account defines "Name", but it was imported as "FullName" about entityType.

```
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: AccountCustomEntity
```

<img width="450" alt="image" src="https://user-images.githubusercontent.com/55295601/161015816-192d91f3-f9ec-4d13-a667-d2c51ced968d.png">

Can you please advise me how to resolve issues? thanks you.
